### ISSUE TITLE
Convert Resource list and Resource detail components to Redux

### ISSUE THREAD

**Issue by twolfe2** [ShelterTechSF/askdarcel-web#122]
We are making repetitive API calls and this can be prevented if we start using Redux for these components

**Comment by Maxastuart** [comment]
@jmpainter can you explore possibly starting here?

**Comment by jmpainter** [comment]
I'm looking at the ResourceEntry and ServiceEntry components, which would most likely be the 'Resource detail' components mentioned. These are connected to the redux store already to get the userLocation and are not making any api calls. Also, the SearchTable component, which I'm guessing would correspond to 'Resource list' is not making any api calls. Maybe this issue is out of date?

**Comment by Maxastuart** [comment]
@jjfreund @richardxia @anyone can you confirm this is out of date & close?

**Comment by Maxastuart** [comment]
@tsyaeger
