### ISSUE TITLE
Clearing a field has no effect

### ISSUE THREAD

**Issue by Kphi** [ShelterTechSF/askdarcel-web#135]
Make edits -> clear phone number field -> save -> ?? did it work?

**Comment by derekfidler** [comment]
Should add clearer calls to action on edit page

**Comment by twolfe2** [comment]
Do we want to show a modal on save?

**Comment by jjfreund** [comment]
We may want to show a modal on save but that should be opened as a different issue. The issue Hicham reported is that the save *fails* if a field value is removed.

**Comment by richardxia** [comment]
@Kphi, did you mean that the admin page incorrectly shows that the before and after phone number are both blank? This is what I see on the admin page when I clear out a phone number:

<img width="1026" alt="screen shot 2017-02-22 at 7 50 08 pm" src="https://cloud.githubusercontent.com/assets/1002748/23244157/3aa17ddc-f938-11e6-8c18-6a3ade974f38.png">

However, the functionality does work, since clicking the checkmark to approve the change request will clear the phone number on the resource page. I'll work on fixing that bug, assuming that it's the one being described here.
