### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by derekfidler** [ShelterTechSF/askdarcel-web#140]
Product decision needed: how to improve search results

Ideas: add user created tags, search more than descriptions and titles

**Comment by derekfidler** [comment]
A lot of issues with search in the vetting session are related to typos, no autocompletion, different ways for saying the same resource (such as acronyms), and resources with multiple locations (such as the public library having a resource page for every location).

**Comment by richardxia** [comment]
Some of these are getting fixed in 1.9, but I think we need to break this up into multiple tickets because the requested changes are broad.

Typos in search queries will be supported in 1.9 via Algolia, and we will be able to model resources with multiple locations, though we'll need to hold a datathon to collapse the existing resources. Not sure how we want to handle acronyms unless if the description includes the acronym itself, in which case normal search would work.
