### ISSUE TITLE
Location shows up incorrectly on the directions page

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#251]
However, it shows up correctly on the resource page's map.

**Comment by twolfe2** [comment]
Are you referring to the directions button?

**Comment by Maxastuart** [comment]
@cliffcrosland did your fix fix this?

**Comment by Maxastuart** [comment]
@fredciaramaglia was just playing around on the staging app and noticed a bug in the location marker on the google map. Go to:
https://askdarcel.org/search?refinementList[categories][0]=Basic%20Needs%20%26%20Shelter
See result 1.) Cooperative Living Apartments
a service offered by Progress Foundation

368 Fell Street
The map icon is near 24th and Capp, nowhere near Fell.  Also the map marker moves a block or so when you enlarge or reduce the map.  This happens on other resources as well.

**Comment by chrisco23** [comment]
There is simply an incorrect lat/long for resource_id 641 in the database.  I'd be glad to fix if someone can give me some guidance on the accepted procedure for making such a correction.

**Comment by fredciaramaglia** [comment]
That may be part of the problem, but there is a second issue:
1. Go to: https://askdarcel.org/search?refinementList[categories][0]=Basic%20Needs%20%26%20Shelter
2. If necessary move the map so that you can see the (1) map location icon for the first resource.
3. Hit the "-" button to shrink the map.  
Note that the (1) icon stays in the same place while the map shrinks and moves, so that it looks as if the resource has moved.

**Comment by fredciaramaglia** [comment]
Related to issue:
https://github.com/ShelterTechSF/askdarcel-web/issues/771

May be duplicate.

**Comment by schroerbrian** [comment]
should be fixed by: https://app.zenhub.com/workspaces/sheltertechsf-56fdff7cea7e6cbe14290492/issues/sheltertechsf/askdarcel-web/771 which addresses the markers moving on zoom in and out

**Comment by Maxastuart** [comment]
Fixed by #771

**Comment by Maxastuart** [comment]
Fixed by #771 & #815
