### ISSUE TITLE
Add delete button for services and resources

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#283]
(actually, it'll just inactivate them).

**Comment by derekfidler** [comment]
would love for this to get into this release. looks bad on the site

![screen shot 2017-10-24 at 18 26 37](https://user-images.githubusercontent.com/2722783/31975857-e779e92a-b8e8-11e7-871a-b2c9a968e500.png)

**Comment by alexanderturinske** [comment]
![image](https://user-images.githubusercontent.com/12485238/33923811-0c03230e-df88-11e7-8f0c-c97cfa128810.png)
I created buttons:
1. the cancel changes navigates back to the previous state
2. the delete service button, which currently doesn't do anything because I am not sure the Save Changes resource can handle deletions

Open questions:
1. If the user clicks the cancel changes button, it would be good to have a modal that would pop up if any changes have been made to ensure the user knows that will lose those changes if they continue. We currently don't have any modals in the application; could I get a mock-up of what we would like the modal to look like? Additionally, should I build the modal from scratch or are we interested in bringing in a library to handle this? @derekfidler @lexholden 
2. Does the /api/resources/resource.id/change_requests handle service deletions? @jjfreund @lgarofalo 
3. Does the /api/resources/resource.id/change_requests handle entire resource deletions? @jjfreund @lgarofalo

**Comment by derekfidler** [comment]
i'd like to make a separate ticket for confirmations on leaving the edit page. I'd like to pop it up for both clicking cancel and back button. (accidentally hitting back button is pretty common at datathons, happens about once a datathon and it's pretty demoralising. 

There is a design for modals that @Garance91540 put together here, but I'm not opposed to using an existing library if it's similar and does the job: https://sheltertech.quip.com/-/blob/GZHAAA3UUSu/E1rxEgoshrtyfSQWsgh--Q?name=Resource%20correct.png

**Comment by alexanderturinske** [comment]
Thanks! That link is broken, btw.
