### ISSUE TITLE
Confirm deleting schedule day for service works

### ISSUE THREAD

**Issue by jjfreund** [ShelterTechSF/askdarcel-web#441]

**Comment by Maxastuart** [comment]
@alexanderturinske was there a PR for this completed and bug free? it's history has me confused now, just close if you know the test is covered

**Comment by alexanderturinske** [comment]
I linked my commit where I created the test for this, but the test should fail because the removing of a schedule time for a service is broken. It never fully removes the time, but instead changes the time to --:--, so once that gets fixed, the test should pass. I will work on that hopefully tomorrow.

I created Issue #594, but someone commented on it saying it was not reproducible. 

I would say then that the remaining work to be done on this is to unskip [this](https://github.com/ShelterTechSF/askdarcel-web/blob/0076107e11a860052f8da751873a4d1dacbe0396/testcafe/service.js#L81) test and see if it works

**Comment by richardxia** [comment]
FWIW, I tried removing the `skip` annotation on that test as part of https://github.com/ShelterTechSF/askdarcel-web/pull/897, but the test is still failing with an error message that suggests that the schedule day isn't actually getting deleted. Basically, it expected that the number of schedule days to go down by 1 after the test runs, but it's still seeing the same number of schedule days.
