### ISSUE TITLE
Update HAP verified component to use verified_at data once API change is made

### ISSUE THREAD

**Issue by lexholden** [ShelterTechSF/askdarcel-web#483]

**Comment by twolfe2** [comment]
@derekfidler I'm thinking we'll just add the date here since the new resource page designs likely won't be done this milestone. Let us know if you think there's a better place for the date though

![image](https://user-images.githubusercontent.com/13949747/47472760-b381f300-d7c4-11e8-87a9-b3f756571511.png)

**Comment by Maxastuart** [comment]
See #824 (MOHCD & HAP want the HAP-verified badges removed)

**Comment by Maxastuart** [comment]
Not a component we're using anymore, might make separate ticket later to connect verified_at data to the edit/admin pages
