### ISSUE TITLE
Fix open hours being offset by an hour

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#665]
Open hours is offset by an hour. Richard mentioned: "Oh, I think we had a hack in the codebase that didn't take into account daylight savings" So... in the switch last weekend we went back on daylight savings and need to rehack that.
example: https://askdarcel.org/resource?id=76 
![Capture1.PNG](https://images.zenhubusercontent.com/5c7315ed218687594435a617/2b76ee5e-57a0-45b2-8b01-6deaae634e0c)
https://askdarcel.org/resource/edit?resourceid=76
![Capture.PNG](https://images.zenhubusercontent.com/5c7315ed218687594435a617/a69d5951-b0ff-4adc-a022-a1d840e6031e)

**Comment by Maxastuart** [comment]
This immediately needs someone who knows the database-time setup to do a quick hack to temporarily make most of them display correctly. We'll redo how the database stores times (and how everything connects to the database) in a nearby future sprint. @richardxia @lexholden

**Comment by cliffcrosland** [comment]
The time appears to be shifted correctly by one hour now. @richardxia is this okay to close?

I'd also be happy to dig into this deeply and build a more permanent fix if that would be helpful.

cc: @Maxastuart 

![Screen Shot 2019-03-27 at 8 13 22 PM](https://user-images.githubusercontent.com/581562/55127295-e1999500-50cc-11e9-85ac-e9614befab7c.png)

**Comment by cliffcrosland** [comment]
Ah nevermind. The times that appear in the form and the times that appear in the resource profile are different by 1 hour. I'll talk to Richard and work on this.

**Comment by cliffcrosland** [comment]
I'd be happy to take on a fairly big project to store times in UTC possibly? Any thoughts? cc @richardxia

**Comment by richardxia** [comment]
Just to record an offline conversation I had with @cliffcrosland on Wednesday, I think the fundamental issue is that a service's hours are not actually any specific point in time but the notion of a recurring time based on the day of the week. Any logic that attempts to represent the open/close times as a time with a year, month, and day is flawed because that would fix the open/close time to a particular date, which may be subject to daylight savings and, even worse, geopolitical changes in timezones.

We are also vulnerable to making assumptions about the open/close times that appear to be safe at first glance, but upon further inspection are not always true. For example, you can't assume that 5am is always 4 hours after 1am; during the beginning or end of daylight savings there could actually be 3 or 5 hours between the two times.

**Comment by richardxia** [comment]
Also, relevant video: https://www.youtube.com/watch?v=-5wpm-gesOY

**Comment by cliffcrosland** [comment]
relevant askdarcel-api PR from @jjfreund: https://github.com/ShelterTechSF/askdarcel-api/pull/400
