### ISSUE TITLE
Bugfix resource inheriting one of it's service's open times

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#673]
Found a bug where a resource inherits one of its service's open times. Upon editing a service's open hours, the resource adopts the new open hours - this should not happen, please see what happened and fix.

**Comment by jjfreund** [comment]
Thanks for taking this issue @drcaramelsyrup! So the issue here is that some old records were imported into the db such that the service and the parent resource both pointed to the same record in the schedules table. 

The easiest way to fix this would be, presumably, to write a sql script or rake task to correct these issues by updating the services to point to blank, empty schedules instead. That will cause them to inherit their schedules correctly from the parent org.
