### ISSUE TITLE
Mobile Friendly Resource Page

### ISSUE THREAD

**Issue by Maxastuart** [ShelterTechSF/askdarcel-web#681]
Make Resource Page mobile friendly, according to @derekfidler 's preliminary design from https://www.figma.com/file/H0kD6ZZPhPR2RMyNJHWWeTtI/Web-Client?node-id=0%3A1 (Tag or Slack him if questions) 
![Screen Shot 2019-03-25 at 22 10 38](https://user-images.githubusercontent.com/31591394/54976138-a8d7af80-4f56-11e9-8498-8ab9dd0f28b3.png)

**Comment by derekfidler** [comment]
I've updated the comps because bottom sticky bars don't work well on mobile Safari. We also have fewer buttons currently so the new design reflects this.

You can view the figma here: https://www.figma.com/file/H0kD6ZZPhPR2RMyNJHWWeTtI/Web-Client?node-id=1456%3A1472

![Screen Shot 2019-03-26 at 17 08 55](https://user-images.githubusercontent.com/2722783/55013977-76779200-4fea-11e9-9b37-2c27a910b3a5.png)
