### ISSUE TITLE
Service status is incorrect mid-day if service has split hours

### ISSUE THREAD

**Issue by fredciaramaglia** [ShelterTechSF/askdarcel-web#769]
On Wednesday 8:51am
Search for: Women's Shelter Program
Status is: Closed Until Tomorrow
Women’s Shelter Program: Re-opens at 6:00pm today
Status should be: Closed Now or Closed Until 6:00pm Today

![image.png](https://images.zenhubusercontent.com/5cdcbb3d22376b7717f71776/a7f75be5-accb-414a-81c6-c4277cda5e1d)

![image.png](https://images.zenhubusercontent.com/5cdcbb3d22376b7717f71776/fddb5304-01c5-4254-936a-4afeda65d8d6)

**Comment by fredciaramaglia** [comment]
Tested again at 7:40am Aug 6 on 1.20 in both staging and production.  This bug still occurs and produces the same result.

**Comment by richardxia** [comment]
After digging into it, I figured out that this is due to bad schedule data in the database. If you look very, very carefully, you can see that Thursday's (and only Thursday's) schedule is configured incorrectly, where instead of having two ranges, one from midnight to 7am and one from 6pm to midnight, it actually says 12pm instead of 12am for the first range. This means that it has two ranges which overlap each other (Th 12p – F 7a and Th 6p – Th 11:59p).

This caused the code to behave strangely since it doesn't really know what to do when it sees two overlap. I fixed this by just updating the incorrect time using the edit page.
