### ISSUE TITLE
Algolia search engine is too loose trying to correct errors

### ISSUE THREAD

**Issue by fredciaramaglia** [ShelterTechSF/askdarcel-web#772]
1. Search for "Curry Senior Center"
Result: Correctly get 6 results:  Curry Senior Center and 5 of its services.
2. Search for "Curry"
Result: Return 99 results; all but the 6 above do not contain "curry"; the search matches anything beginning with "curr", including "currently", "curriculum", ...

Is there any way to tighten this up?

**Comment by fredciaramaglia** [comment]
Other confusing results:
1. Search for 'dental care' returns 248 results, most of which have nothing to do with dental care.
2. Search for 'dental' returns 320 results, ditto.
3. Search with 'thex' returns (maxes out at) 1000 results, perhaps searching for 'the'?

It seems as if Algolia is doing a fuzzy search using the root of the work.  This is extremely confusing and somehow we need to tighten this up.

**Comment by quanhuynh** [comment]
@fredciaramaglia i figured out the issue with 'dental'
algolia by default takes into account typos. for 'dental', it was looking for 'dental' and 'mental' as well. there are about 40ish 'dental' results, and the rest came from 'mental' and 'rental'. also by default, the exact matches ('dental') show up first, but because we have a custom rule to feature the MOHCD-funded results first, the 'mental'/'rental' results marked as MOHCD-funded are the first ones

one quick solution is that for keywords that we find like 'dental', we can turn off typo checking

**Comment by fredciaramaglia** [comment]
Hi Quan,

I went to algolia.com and found a lot of information about typo tolerance:
https://www.algolia.com/doc/guides/managing-results/optimize-search-results/typo-tolerance/#typos-and-spelling-errors ; and:

https://www.algolia.com/doc/guides/managing-results/optimize-search-results/typo-tolerance/in-depth/configuring-typo-tolerance/

I have noticed a lot of bad results from loose fuzzy searches.  I think it is better to tighten up the defaults for algolia.  Take a look.  I think it may be better to adjust TypoTolerance  and MinWordSizefor1Typo.  This would solve a lot of related problems and we wouldn’t have to special case a lot of words.

Let me know what you think.

Thanks,
Fred

**Comment by Maxastuart** [comment]
I just set TypoTolerance to 'min' on Stagins & Prod, it seems to have accomplished everything we and MOHCD wanted with regard to typos. One benefit to this setting is only perfect matches will be returned, unless no perfect match results are found, then results with 1 typo will be returned, unless none of those are found too, only then will results with 2 typos be returned
@fredciaramaglia @quanhuynh

**Comment by quanhuynh** [comment]
@Maxastuart Awesome!!
