### ISSUE TITLE
Search filter - some Eligibilities check boxes are not clickable

### ISSUE THREAD

**Issue by fredciaramaglia** [ShelterTechSF/askdarcel-web#774]
From home page click on the Basic Needs & Shelter category and then click on Filters.

Some of the Eligibilities check boxes are clickable e.g., "Homeless" and "LGBTQ", and some are not, e.g. "Disability" and "Families"

**Comment by fredciaramaglia** [comment]
Functions as designed.  Checkboxes with no results are not clickable.

**Comment by Maxastuart** [comment]
actually this is a bug! re-opening!

**Comment by quanhuynh** [comment]
more details:
so in the code, the logic is that a checkbox is supposed to be checkable if there are results for **at least one** element that was mapped to that checkbox name (for example, if there are results for Developmental Disability, the checkbox Disability should be checkable; if there are results for Families with Babies, the checkbox Families should be checkable)
however, there is a bug. i can directly go to https://askdarcel.org/search?refinementList[eligibilities][0]=Developmental%20Disability to see results for the eligibility Developmental Disability, and the Disability box is shown checked. but I cannot check on the Disability box in the first place.

this leads me to think that the mapping isn't broken, since the Disability box is checked in that URL. it's just the initial logic (before checking the box) that is buggy.

fyi @schroerbrian. maybe you came across something i missed while graying out the checkboxes

**Comment by quanhuynh** [comment]
figured out the issue:
by default, algolia refinements only return 10 values, so that's why some of the eligibilities/categories aren't clickable, because they were never given to the frontend, even though they exist in the DB. going to increase this limit and make some minor changes in a PR

fyi @Maxastuart
