### ISSUE TITLE
On the ressources/result page we should filter out results that are >x miles away from current position

### ISSUE THREAD

**Issue by hichamsab** [ShelterTechSF/askdarcel-web#85]
As a result, if there's no result in my vicinity, I should get an empty list

**Comment by lgarofalo** [comment]
Related to #90 , probably same back end implementation controlled via query param? @achadha

**Comment by Maxastuart** [comment]
I was thinking, for now we still want results to pop up as some people may search from outside the city for friends/family in the city, or maybe caseworkers working remotely, etc. 

We should hold off on implementing this until we add a "near ____" filter where you can type in what you want to search near, instead of forcing near me (near me should be an option, but a textbox accepting any city or service is possible to add too).

In addition, there are certain services that may be online-only and when they are ranked high or labeled featured, etc., we want them to show up in all searches regardless of location (as long as we're still serving just the bay area)
